# Generated by Django 2.0 on 2017-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myId', models.IntegerField()),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
